<a href="https://colab.research.google.com/github/ARC040306/Metodos-Numericos-I/blob/main/Factorizaci%C3%B3n_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

n = int(input("Ingrese el tamaño de la matriz cuadrada (n): "))
print("Ingrese los elementos de la matriz A fila por fila (separados por espacios):")
A = np.array([list(map(float, input(f"Fila {i + 1}: ").split())) for i in range(n)])

# Verificamos que la matriz sea cuadrada
if A.shape != (n, n):
    print("La matriz ingresada no es cuadrada.")
else:
    # Inicializamos las matrices L y U
    L = np.eye(n)
    U = np.zeros((n, n))

    for i in range(n):
        pivot = A[i, i] - sum(L[i, k] * U[k, i] for k in range(i))
        if pivot == 0:
            print("Factorización no posible: el pivote es cero.")
            break
        L[i, i] = 1
        U[i, i] = pivot

        #Calculando la i-ésima fila de U
        for j in range(i + 1, n):
            U[i, j] = (A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))) / L[i, i]

        #Calculando la i-ésima columna de L
        for j in range(i + 1, n):
            L[j, i] = (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]

    print("\nMatriz L:")
    print(L)
    print("\nMatriz U:")
    print(U)


Ingrese el tamaño de la matriz cuadrada (n): 4
Ingrese los elementos de la matriz A fila por fila (separados por espacios):
Fila 1: 1 1 0 3
Fila 2: 2 1 -1 1
Fila 3: 3 -1 -1 2
Fila 4: -1 2 3 -1

Matriz L:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U:
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
