<a href="https://colab.research.google.com/github/ARC040306/Metodos-Numericos-I/blob/main/Tutorial_basico_numpy_RCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

# np.array() convierte una lista o lista de listas en un arreglo de NumPy
arr = np.array([1, 2, 3, 4, 5])
print("Arreglo a partir de lista:", arr)

# np.zeros() crea un arreglo con todos sus elementos igual a 0
zeros = np.zeros((2, 3))  # 2 filas y 3 columnas
print("\nArreglo de ceros:\n", zeros)

# np.ones() crea un arreglo con todos sus elementos igual a 1
unos = np.ones((3, 2))  # 3 filas y 2 columnas
print("\nArreglo de unos:\n", unos)

# np.linspace() genera un arreglo de números igualmente espaciados entre un rango
linspace_arr = np.linspace(0, 10, 5)  # De 0 a 10, con 5 elementos
print("\nArreglo linspace:", linspace_arr)

# np.random.rand() genera un arreglo con valores aleatorios de una distribución uniforme en el intervalo [0, 1)
aleatorio = np.random.rand(2, 2)  # 2 filas y 2 columnas
print("\nArreglo aleatorio:\n", aleatorio)

# np.max() retorna el valor máximo de un arreglo
maximo = np.max(arr)
print("\nValor máximo del arreglo:", maximo)

# np.min() retorna el valor mínimo de un arreglo
minimo = np.min(arr)
print("\nValor mínimo del arreglo:", minimo)

# np.sum() retorna la suma de los elementos de un arreglo
suma_interna = np.sum(arr)
print("\nSuma de los elementos:", suma_interna)

# np.mean() retorna el valor medio de los elementos de un arreglo
medio = np.mean(arr)
print("\nMedia de los elementos:", medio)

# np.reshape() cambia la forma del arreglo sin alterar sus datos
reacomodo = np.reshape(arr, (5, 1))  # Cambia el arreglo a una matriz de 5x1
print("\nArreglo reconfigurado:\n", reacomodo)

# np.add() suma elemento por elemento de dos arreglos
arr2 = np.array([5, 4, 3, 2, 1])
suma_vectores = np.add(arr, arr2)
print("\nSuma de dos arreglos:", suma_vectores)

# np.dot() calcula el producto punto entre dos arreglos
producto_punto = np.dot(arr, arr2)
print("\nProducto punto de dos arreglos:", producto_punto)

# np.arange() genera un arreglo de números enteros en un rango definido
range_arr = np.arange(0, 10, 2)  # De 0 a 10, con paso 2
print("\nArreglo con rango:", range_arr)

# np.argmax() retorna el índice del valor máximo de un arreglo
indice_maximo = np.argmax(arr)
print("\nÍndice del valor máximo:", indice_maximo)

# np.resize() cambia el tamaño del arreglo, rellenando con ceros si es necesario
redimensionado = np.resize(arr, (2, 3))  # Cambia a 2 filas y 3 columnas
print("\nArreglo redimensionado:\n", redimensionado)


Arreglo a partir de lista: [1 2 3 4 5]

Arreglo de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Arreglo de unos:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Arreglo linspace: [ 0.   2.5  5.   7.5 10. ]

Arreglo aleatorio:
 [[4.31660558e-01 7.14005972e-04]
 [8.19161276e-01 9.10864751e-01]]

Valor máximo del arreglo: 5

Valor mínimo del arreglo: 1

Suma de los elementos: 15

Media de los elementos: 3.0

Arreglo reconfigurado:
 [[1]
 [2]
 [3]
 [4]
 [5]]

Suma de dos arreglos: [6 6 6 6 6]

Producto punto de dos arreglos: 35

Arreglo con rango: [0 2 4 6 8]

Índice del valor máximo: 4

Arreglo redimensionado:
 [[1 2 3]
 [4 5 1]]
